services:
  api:
    build: .
    container_name: todo-api
    environment:
      - UV_SYSTEM_PYTHON=1
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
